const GENERIC_TITLE_BLOCKLIST = new Set([
    'game',
    'game.exe',
    'game.x86_64',
    'game.sh',
    'start.sh',
    'run.sh',
    'launch.sh',
    'apprun',
    'start',
    'start.exe',
    'launch',
    'launch.exe',
    'build',
    'windows',
    'win64',
    'win32',
    'linux',
    'linux64',
    'x86_64',
    'x86',
    'release',
    'bin',
    'data',
    'www',
    'nwjs',
    'nw.js',
    'unity',
    'unity player',
    'unitycrashhandler',
    'unitycrashhandler64',
    'crashhandler',
    'crashpad',
    'updater',
    'godot',
    'godot engine',
    'main',
    'main.exe',
    'app',
    'app.exe',
    'application',
    'rmmz-game',
    'rmmv-game',
    'electron',
    'default',
    'my game',
    'test',
    'untitled',
    'rpg maker mv',
    'rpg maker mz'
]);

export function isGenericOrEmptyTitle(title: string | null | undefined): boolean {
    if (!title || typeof title !== 'string') return true;
    const normalized = title.trim().toLowerCase();
    if (!normalized) return true;
    return GENERIC_TITLE_BLOCKLIST.has(normalized);
}
