packages:
  - 'packages/*'

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - extract-file-icon

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  extract-file-icon: true
