sonar.organization=loerei
sonar.projectKey=loerei_YumeShelf
sonar.projectName=YumeShelf
sonar.sources=src,native
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts, tests/**/*.spec.ts
sonar.exclusions=node_modules/**, dist/**, build/**, build_output/**, tests/**, **/*.test.ts, **/*.spec.ts, src/main/core/lz-string.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
